#include "main.h"

BSDATA(traiti) = {
	{"BargeThrought", 3},
	{"MeanStreak", 2},
	{"SuckerPunch", 2},
	{"Inventor", 0},
	{"Motorhead", 3},
	{"Tinkerer", 2},
	{"MonsterHunter"},
	{"RotFinder", 0},
	{"Scavenger", 2},
	{"JuicyInfo", 2},
	{"ViciousCreep", 3},
	{"WheelerDealer", 1},
	{"BloodHound", 1},
	{"FightDog", 1},
	{"MutantsBestFriend", 1},
	{"Agitator", 1},
	{"BoneSaw", 3},
	{"Perfomer", 1},
	{"Commander", 1},
	{"Gunslingers", 3},
	{"Racketeer", 1},
	{"Cynic", 1},
	{"Rebel", 0},
	{"Resilent", 1},
	{"Admirer", 0},
	{"Archeologist", 0},
	{"BadOmens", 1},
	{"Bodyguard", 1},
	{"Butcher", 1},
	{"CombatVeteran", 3},
	{"CoolHead", 1},
	{"Counselor", 3},
	{"Coward", 1},
	{"FastDraw", 2},
	{"Flyweight", 2},
	{"Gadgeteer", 2},
	{"GoodFootwork", 2},
	{"HardHitter", 0},
	{"Workhorse", 0},
	{"JackOfAllTrade", 0},
	{"LightEater", 0},
	{"Loner", 0},
	{"NeverSurrender", 0},
	{"PackMule", 2},
	{"PersonalArithmetic", 3},
	{"Sharpshooter", 3},
	{"Sleepless", 3},
	{"Stoic", 2},
	{"Therapist", 2},
	{"WeaponSpecialist", 2},
	{"ZoneCook", 2},
};
BSDATAF(traiti)